.TH man 1 "Aug 2023" "1.1" "dbak man page"

.SH NAME
dbak \- backup the files and folders using rsync/borg

.SH SYNOPSIS
.B dbak [OPTIONS]

.SH DESCRIPTION
Backup all files and folders specified in the configuration
file, using rsync. Essentially this is a simple wrapper around
rsync and borg to make it easier to perform automatic backups.

The configuration file ignores leading and trailing whitespace,
empty lines and lines starting with #. All paths must be absolute
to be valid. The first valid line must specify the destination
directory and all other lines can be either individual files or
directory paths, like so:

    # Destination
    /media/user/external_disk/Backups

    # Some configuration files
    /home/user/.bashrc
    /home/user/.nanorc

    # Some directories
    /home/user/.config/
    /etc/

.SH OPTIONS

.TP
.B \-h
print usage information and exit

.TP
.B \-c FILE
specify a different configuration file path. Default is ~/.config/dbak

.TP
.B \-b
use borg backup and repositories instead of rsync

.TP
.B \-r TIME
borg archive retention, given as an int and unit (1y,3m,...). Default is 3m

.TP
.B \-z STD[,N]
compression standard to use for borg archives, optionally with compression
quality. Default is zstd (Run 'borg help compression' for more details)

.TP
.B \-e MODE
set borg encryption mode. Default is repokey (See man 1 borg-init for mroe details)

.SH SEE ALSO
rsync(1) borg(1) borg-init(1) borg-create(1) borg-prune(1) borg-compact(1)

.SH AUTHOR
Marios Tsolekas <marios.tsolekas@gmail.com>

.SH REPORTING BUGS
Report bugs to <https://github.com/mtsolekas/dbak/issues>

.SH COPYRIGHT
This program is free software. You can redistribute it and/or modify
it under the terms of the GNU GPL version 3 or (at your option)
any later version. There is NO warranty, not even MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.
See http://gnu.org/licenses/gpl.html
